# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Hotel' do
pod 'RestKit', '~> 0.24.0'
pod 'TNRadioButtonGroup'
pod 'RESideMenu'
end

target 'HotelTests' do

end

target 'HotelUITests' do

end

